name: vagrant-up

on:
  push:
    branches:
      - main

jobs:
  vagrant-up:
    runs-on: macos-10.15

    steps:
      - uses: actions/checkout@v2

      - name: Cache Vagrant boxes
        uses: actions/cache@v2
        with:
          path: ~/.vagrant.d/boxes
          key: ${{ runner.os }}-vagrant-${{ hashFiles('Vagrantfile') }}
          restore-keys: |
            ${{ runner.os }}-vagrant-

      - name: Add VirtualBox conf
        run: echo "* 10.0.0.0/8 192.168.0.0/16 172.16.0.0/12" > /etc/vbox/networks.conf   
        
      - name: Show Vagrant version
        run: vagrant --version

      - name: Run vagrant up
        run: vagrant up --provider=virtualbox

      - name: ssh into box after boot
        run: vagrant ssh k8s-controller -c "kubectl get nodes"
