name: Vagrant Up

on:
  push:
    branches:
      - main

jobs:
  vagrant-up:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Show Vagrant version
        run: vagrant --version

      - name: Run vagrant up
        run: vagrant up

      - name: ssh into box after boot
        run: vagrant ssh k8s-controller-1 -c "kubectl get nodes"
